name: dependencies
on:
  push:
  schedule:
    - cron: '15 0 * * 0'   # Once per week, at 15 past midnight on Sunday - see https://crontab.guru/#15_0_*_*_0

jobs:
  antq:
    runs-on: ubuntu-latest
    container:
      image: uochan/antq
    steps:
      - uses: actions/checkout@v2
      - run: java -jar /tmp/antq/antq.jar --skip=pom --error-format="::error file={{file}}::{{message}}"
