name: vulnerabilities
on:
  push:
  pull_request:
  schedule:
    - cron: '0 2 * * 2'   # Every Tuesday at 2am

jobs:
  skip_check:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master

  vulnerabilities:
    needs: skip_check
    if: ${{ needs.skip_check.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0    # Make sure we get the full history, or else the version number gets screwed up
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: DeLaGuardo/setup-clojure@10.2
        with:
          cli: latest
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn') }}

      - name: Run NVD vulnerabilities check
        run: clojure -Srepro -J-Dclojure.main.report=stderr -T:build nvd
