name: vulnerabilities
on:
  push:
  pull_request:
  schedule:
    - cron: '0 21 * * 0'

jobs:
  vulnerabilities:
    runs-on: ubuntu-latest
    environment: clojars

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      - uses: DeLaGuardo/setup-clojure@10.2
        with:
          cli: latest
      - uses: actions/cache@v3
        with:
          path: |
            ~/.m2/repository
            ~/.gitlibs
            ~/.clojure
            ~/.cpcache
          key: ${{ runner.os }}-${{ hashFiles('**/deps.edn') }}

      - name: Run NVD vulnerabilities check
        run: clojure -Srepro -J-Dclojure.main.report=stderr -T:build nvd
